#!/bin/sh
#
# chkconfig: - 99 01
# description: start_proj_with_os
#
. /lib/lsb/init-functions
### BEGIN INIT INFO
# Provides: OSSEC HIDS
# Required-Start: $network $remote_fs $syslog $time
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: OSSEC HIDS
### END INIT INFO

start () {
    cd /root/proj_path/PoolMonitor && python Get_Conf.py
}

stop () {

    for pid in ` ps ax |grep cgminer |sed -e 's/ *//' -e 's/ .*//' `
        do
        kill -9 $pid
        done

}


case "$1" in
    start)
        start
        exit $?
        ;;

    stop)
        stop
        exit $?
        ;;
    restart)
       start
       sleep 3
       stop
       exit $?
       ;;

    *)
        echo "Unknown command: $command" >&2
        echo 'Valid commands are: start, stop' >&2
        exit 1
esac
